version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: chat_redis
    ports:
      - "6380:6379"

  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_fastapi
    expose:
      - "8001"
    volumes:
      - ./auth_service:/app
    environment:
      - REDIS_URL=redis://redis:6379 # 👈 Corregido
    depends_on:
      - redis

  chat-backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: chat_fastapi
    expose:
      - "8000"
    depends_on:
      - redis
      - auth-service
    environment:
      - REDIS_URL=redis://redis:6379 

  nginx-proxy:
    build:
      context: ./app/nginx
      dockerfile: Dockerfile
    container_name: chat_nginx
    ports:
      - "80:80"
    volumes:
      - ./app/frontend:/usr/share/nginx/html
    depends_on:
      - chat-backend
      - auth-service